export REPLACERESOLVER_LOCATION="$1"

export PYTHONPATH=$REPLACERESOLVER_LOCATION/lib/python2.7/site-packages:$PYTHONPATH
export PXR_PLUGINPATH_NAME="$REPLACERESOLVER_LOCATION/resources:$PXR_PLUGINPATH_NAME"

