#ifndef HELLO_RESOLVER_DEBUGCODES_H
#define HELLO_RESOLVER_DEBUGCODES_H

#include "pxr/pxr.h"
#include "pxr/base/tf/debug.h"

PXR_NAMESPACE_OPEN_SCOPE


TF_DEBUG_CODES(
    HELLORESOLVER_PATH,
    HELLORESOLVER_REPLACE
);


PXR_NAMESPACE_CLOSE_SCOPE

#endif // HELLO_RESOLVER_DEBUGCODES_H
