// Copyright 2019 Rodeo FX.  All rights reserved.
#ifndef REPLACE_RESOLVER_DEBUGCODES_H
#define REPLACE_RESOLVER_DEBUGCODES_H

#include <pxr/pxr.h>
#include <pxr/base/tf/debug.h>

PXR_NAMESPACE_OPEN_SCOPE


TF_DEBUG_CODES(
    REPLACERESOLVER_PATH,
    REPLACERESOLVER_REPLACE,
    REPLACERESOLVER_CURRENTCONTEXT
);


PXR_NAMESPACE_CLOSE_SCOPE

#endif // REPLACE_RESOLVER_DEBUGCODES_H
